Notes: Jenkins pipeline
services:
  backend:
    version: develop-4.7.0-26
    image: develop-4.7.0-26
    buildNumber: '26'
  frontend:
    version: develop-3.8.0-16
    image: develop-3.8.0-16
    buildNumber: '16'
