Notes: Jenkins pipeline
project: bento
services:
  backend:
    version: 4.9.0.259
    image: 4.9.0.259
    buildNumber: '259'
  frontend:
    version: 3.10.0.132
    image: 3.10.0.132
    buildNumber: '132'
  auth:
    version: 2.2.0.35
    image: 2.2.0.35
    buildNumber: '35'
  files:
    version: 2.2.0.48
    image: 2.2.0.48
    buildNumber: '48'
  users:
    version: 1.3.0-develop.46
    image: 1.3.0-develop.46
    buildNumber: '46'
