Notes: Jenkins pipeline
project: bento
services:
  backend:
    version: 4.10.0.271
    image: 4.10.0.271
    buildNumber: '271'
  frontend:
    version: 4.0.0.163
    image: 4.0.0.163
    buildNumber: '163'
  auth:
    version: 2.2.0.35
    image: 2.2.0.35
    buildNumber: '35'
  files:
    version: 2.2.0.48
    image: 2.2.0.48
    buildNumber: '48'
  users:
    version: 1.3.0-develop.61
    image: 1.3.0-develop.61
    buildNumber: '61'
