Notes: Jenkins pipeline
project: bento
services:
  backend:
    version: 4.10.0.281
    image: 4.10.0.281
    buildNumber: '281'
  frontend:
    version: 4.0.0.182
    image: 4.0.0.182
    buildNumber: '182'
  auth:
    version: 2.3.0.50
    image: 2.3.0.50
    buildNumber: '50'
  files:
    version: 2.2.0.48
    image: 2.2.0.48
    buildNumber: '48'
  users:
    version: 1.3.0.69
    image: 1.3.0.69
    buildNumber: '69'
