Notes: Jenkins pipeline
project: bento
services:
  backend:
    version: 4.10.0.275
    image: 4.10.0.275
    buildNumber: '275'
  frontend:
    version: 4.0.0.178
    image: 4.0.0.178
    buildNumber: '178'
  auth:
    version: 2.3.0-develop.40
    image: 2.3.0-develop.40
    buildNumber: '40'
  files:
    version: 2.2.0.48
    image: 2.2.0.48
    buildNumber: '48'
  users:
    version: 1.3.0.66
    image: 1.3.0.66
    buildNumber: '66'
