Notes: Jenkins pipeline
project: bento
services:
  backend:
    version: 4.10.0.281
    image: 4.10.0.281
    buildNumber: '281'
  frontend:
    version: stats_bar_icons.193
    image: stats_bar_icons.193
    buildNumber: '193'
  auth:
    version: 2.3.0.50
    image: 2.3.0.50
    buildNumber: '50'
  files:
    version: file_download_acl.55
    image: file_download_acl.55
    buildNumber: '55'
  users:
    version: 1.3.0.70
    image: 1.3.0.70
    buildNumber: '70'
